<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Interest;

class InterestSeeder extends Seeder
{
    public function run()
    {
        $interests = [
    'Arte',
    'Música',
    'Deportes',
    'Cocina',
    'Viajes',
    'Lectura',
    'Ciencia ficción',
    'Tecnología',
    'Moda',
    'Fotografía',
    'Danza',
    'Teatro',
    'Historia',
    'Filosofía',
    'Política',
    'Economía',
    'Psicología',
    'Sociología',
    'Idiomas',
    'Astronomía',
    'Ecología',
    'Reciclaje',
    'Bricolaje',
    'Jardinería',
    'Animales',
    'Voluntariado',
    'Activismo',
    'Emprendimiento',
    'Negocios',
    'Marketing',
    'Gastronomía',
    'Fitness',
    'Yoga',
    'Salud',
    'Espiritualidad',
    'Cine',
    'Videojuegos',
    'Pintura',
    'Escritura',
    'Poesía',
    'Natación',
    'Senderismo',
    'Running',
    'Ciclismo',
    'Buceo',
    'Equitación',
    'Golf',
    'Tenis',
    'Fútbol',
    'Baloncesto',
    'Voleibol',
    'Béisbol',
    'Hockey',
    'Rugby',
    'Cricket',
    'Artesanía',
    'Repostería',
    'Coctelería',
    'Vinicultura',
    'Modelismo',
    'Robótica',
    'Realidad virtual',
    'Criptomonedas',
    'Desarrollo web',
    'Diseño gráfico',
    'Edición de video',
    'Podcasting',
    'Streaming',
    'Medicina',
    'Veterinaria',
    'Derecho',
    'Periodismo',
    'Redes sociales',
    'Investigación científica',
    'Arqueología',
    'Fantasía',
    'Literatura',
    'Artes visuales',
    'Manualidades',
    'Deportes extremos',
    'Aviación',
    'Escultura',
    'Dibujo',
    'Diseño industrial',
    'Diseño de moda',
    'Diseño de interiores',
    'Historia del arte',
    'Historia de la música',
    'Historia del cine',
    'Historia de la fotografía',
    'Gastronomía internacional',
    'Cocina gourmet',
    'Cocina saludable',
    'Cocina vegetariana',
    'Cocina vegana',
    'Marvel',
        ];

        foreach ($interests as $interest) {
            Interest::create(['name' => $interest]);
        }
    }
}
